---
storage:
  trace:
    backend: s3
    s3:
      access_key: "grafana-tempo"
      secret_key: "supersecret"
      bucket: "tempo-traces"
      endpoint: "tempo-minio:9000"
      insecure: true
# MinIO storage configuration
# Note: MinIO should not be used for production environments. This is for demonstration purposes only.
minio:
  enabled: true
  mode: standalone
  rootUser: grafana-tempo
  rootPassword: supersecret
  buckets:
    # Default Tempo storage bucket
    - name: tempo-traces
      policy: none
      purge: false

traces: # Based on yout tracing protocol, enable one of them, (otlp|zipkin|jaeger|opencensus). in this example i enabled otlp http and grpc traces
  otlp:
    grpc:
      enabled: true # Enable Tempo to ingest Open Telemetry GRPC traces
    http:
      enabled: true # Enable Tempo to ingest Open Telemetry HTTP traces
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false
