---
storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-data
      # Format: http://<helm-release-name>-minio:9000
      # If you install with 'helm install tempo grafana/tempo', use 'tempo-minio'
      endpoint: http://tempo-minio:9000
      access_key: tempo
      secret_key: tempo123
      insecure: true # Internal MinIO usually runs on HTTP, so this must be true

minio:
  enabled: true # Tempo helm chart deploys minio by default, if you prefer to use your own mimio instance, disable it as i did
  accessKey: "tempo"    # Create the user for the internal instance
  secretKey: "tempo123" # Create the password for the internal instance
  buckets:
    - name: tempo-data  # Automatically create the bucket on startup
      policy: none
      purge: false

traces: # Based on yout tracing protocol, enable one of them, (otlp|zipkin|jaeger|opencensus). in this example i enabled otlp http and grpc traces
  otlp:
    grpc:
      enabled: true # Enable Tempo to ingest Open Telemetry GRPC traces
    http:
      enabled: true # Enable Tempo to ingest Open Telemetry HTTP traces
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false
